name: "Modbus <=> MQTT"
description: "Service converts RTU and TCP Modbus to MQTT from other 22"
version: 0.16.57
image: ghcr.io/volkmarnissen/modbus2mqtt
url: https://github.com/volkmarnissen/modbus2mqtt/main/introduction.md
webui: http://[HOST]:[PORT:3000]
panel_icon: mdi:arrow-left-right-bold-outline
slug: modbus2mqtt
arch:
  - aarch64
  - amd64
services:
  - mqtt:want
map:
  - share:rw
  - config:rw
  - ssl:rw
hassio_api: true
hassio_role: default
uart: true
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
ports:
  502/tcp: null
  22/tcp: null
ports_description:
  502/tcp: "TCP Bridge port"
  22/tcp: "SSH port to expose on host (if host_network is false)"
options:
  ssh_port: 22
  user_pubkey: ""
schema:
  ssh_port: int(22, 65535)
  user_pubkey: str?
ports:
  22/tcp: null
ports_description:
  22/tcp: "SSH port to expose on host (if host_network is false)"  
